### ISSUE TITLE
Quick Explanation for Each Parameter?

### ISSUE THREAD

**Issue by windowshopr** [Valdecy/pyVRP#1]
Just came across this repo and love it! Would love to get some quick explanations of what each of these parameters do specifically (would save me a lot of time :D ):

# Parameters - Model
time_window = 'without'           # 'with', 'without'
route       = 'closed'            # 'open', 'closed'
 
# Parameters - Vehicle
fixed_cost    = [   17, 2   ]     # Fixed Cost
variable_cost = [    8, 1   ]     # Variable Cost
capacity      = [  950, 750 ]     # Capacity of the Vehicles
fleet_size    = [   10, 10  ]     # Available Vehicles

Thanks a lot!

**Comment by Valdecy** [comment]
Thank you very much! I have expanded the readme file, explaining each parameter.
