### ISSUE TITLE
Able to Add in Priority for Each Demand?

### ISSUE THREAD

**Issue by windowshopr** [Valdecy/pyVRP#2]
Figured I would open this in a second issue, but I would absolutely love to see one of these Colab notebooks incorporate a "priority", along with the demand, for each location. Such that, the locations with higher "priority" are considered as the first stops in the route, before the ones with lower priority. I got the idea from the abstract of this link:

[https://link.springer.com/article/10.1007/s11590-012-0553-x](url)

I envision this "priority" column could act as a sort of "date" filter, whereby the higher the number, the "sooner" that location would be visited to have their demand met. This functionality would make what I'm looking for a million times easier and save so much time! Would love to hear your thoughts. Thanks!!!

**Comment by Valdecy** [comment]
I get it! I think I can implement that request

**Comment by windowshopr** [comment]
I was wondering that very thing when I was playing with the notebooks last night, and now I’ve read your updated readme on the main page and see that’s exactly what I could use! This is perfect, I will keep toying with the parameters but yes that would work perfectly! Thanks! 

I do have another idea similar to this one, and wonder what you might think about it. Let’s say for simplicity we’re using 1 vehicle with enough capacity to deliver to say 10 nodes, however, let’s say that there is only so much time in the day, and the vehicle can only make 5 nodes before the “end of a work day”. They don’t need to come back to the depot as they still have enough load, just ran out of time on day 1. So they finish their delivery to the remaining 5 nodes “tomorrow” before returning the depot. 

Maybe this could be used with the time windows, but I envision on the plot, if the full delivery takes place over 2 days, the plot would have 2 different coloured lines, and the report might have another column that has “Day” as a header and then 1 and 2 denoting which days the deliveries happened. This would simulate the driver had to spend an overnight trip somewhere near the 5th node, and then starting up again the next day, kind of thing? 

Hopefully that makes sense, but I would love to hear your thoughts because this repo is by far the closest thing I’ve seen to a working example of a mTSP program that I could see implementing in the company I work for that coordinates/schedules travelling technicians. And this functionality, coupled with the time window/priority functionality would be absolutely perfect! 👍

**Comment by windowshopr** [comment]
I actually think I may have a hint. I do notice that, if 1 vehicle returns to the 1 and only depot due to wait times, the colour will change, so I'm wondering if that kind of logic for changing colours could be used if, say, "sum of travel time for 'today'" > "working day duration", or some other kind of variable where the user could denote how long a working day is?

**Comment by Valdecy** [comment]
Well, I understand your point, however, these plots were made taking into consideration the routes of each vehicle (each route is identified by color) .  Therefore a route with many colors may be confusing if the problem in question has a lot of overlapping routes. In your specific case, for a given solution, you can customize a function to plot the routes with the 'working day' characteristic. Just check the function:  "plot_tour_coordinates"  as a template for modification.

**Comment by windowshopr** [comment]
That works, I'm getting these same ideas as I'm working with the notebook! Thanks for the support! Great repo!
