### ISSUE TITLE
Fixed an Issue with Report Totalling

### ISSUE THREAD

**Issue by windowshopr** [Valdecy/pyVRP#3]
Hey again!

I noticed an issue with the final report. If multiple subroutes are generated in the solution (say for 2 or more vehicles) the report totals were only showing the totals for the bottom subroute, not the total of ALL vehicles in the report. I don't know how to submit a fix request, but basically I just changed these lines in the `show_report` function of  `pyVRP.py`:

```
            if (j == len(subroute[0]) - 1):
                activity = 'finish'
                if (time[j] > tt):
                    tt = time[j]
                td = td + dist[j]
                tc = tc + cost[j]
```

to...

```
            if (j == len(subroute[0]) - 1):
                activity = 'finish'
                if (time[j] > 0):
                    tt += time[j]
                td += dist[j]
                tc += cost[j]
```

This made the final report show the total values at the bottom to be the sum of each subroute. Can close this issue when you see it. Thanks! Great work on this, I'm having lots of fun with it!

**Comment by windowshopr** [comment]
Nope I lied, the above works for the summing of the "Time" and "Distance" column, but not the "Cost" column as each value in the "Cost" is independent, so the total sum of each value (not just the last value) needs to happen.

To fix, just add a `tc += cost[j]` below the `if (j > 0 and j < len(subroute[0]) - 1):` so the full new function should look like this:

```
# Function: Solution Report
def show_report(solution, distance_matrix, parameters, duration_matrix, fixed_cost, variable_cost, route, time_window):
    column_names = ['Route', 'Vehicle', 'Activity', 'Job', 'Arrive_Load', 'Leave_Load', 'Wait_Time', 'Arrive_Time','Leave_Time', 'Distance', 'Costs']
    tt           = 0
    td           = 0 
    tc           = 0
    tw_st        = parameters[:, 3]
    report_lst   = []
    for i in range(0, len(solution[1])):
        dist         = evaluate_distance(distance_matrix, solution[0][i], solution[1][i])
        wait, time   = evaluate_time(distance_matrix, parameters, solution[0][i], solution[1][i], duration_matrix = duration_matrix)
        reversed_sol = copy.deepcopy(solution[1][i])
        reversed_sol.reverse()
        cap          = evaluate_capacity(parameters, solution[0][i], reversed_sol) 
        cap.reverse()
        leave_cap = copy.deepcopy(cap)
        for n in range(1, len(leave_cap)-1):
            leave_cap[n] = cap[n+1] 
        cost = evaluate_cost(dist, wait, parameters, solution[0][i], solution[1][i], fixed_cost = [fixed_cost[solution[2][i][0]]], variable_cost = [variable_cost[solution[2][i][0]]], time_window = time_window)
        if (route == 'closed'):
            subroute = [solution[0][i] + solution[1][i] + solution[0][i] ]
        elif (route == 'open'):
            subroute = [solution[0][i] + solution[1][i] ]
        for j in range(0, len(subroute[0])):
            if (j == 0):
                activity    = 'start'
                arrive_time = round(time[j],2)
            else:
                arrive_time = round(time[j] - tw_st[subroute[0][j]] - wait[j],2)
            if (j > 0 and j < len(subroute[0]) - 1):
                activity = 'service'
                tc += cost[j]
            if (j == len(subroute[0]) - 1):
                activity = 'finish'
                if (time[j] > 0):
                    tt += time[j]
                td += dist[j]
                tc += cost[j]
            report_lst.append(['#' + str(i+1), solution[2][i][0], activity, subroute[0][j], cap[j], leave_cap[j], round(wait[j],2), arrive_time, round(time[j],2), round(dist[j],2), round(cost[j],2) ])
        report_lst.append(['-//-', '-//-', '-//-', '-//-','-//-', '-//-', '-//-', '-//-', '-//-', '-//-', '-//-'])
    report_lst.append(['TOTAL', '', '','', '', '', '', '', round(tt,2), round(td,2), round(tc,2)])
    report_df = pd.DataFrame(report_lst, columns = column_names)
    return report_df
```

There we go. :D

**Comment by Valdecy** [comment]
Hello There!

Well talking about the time for subroutes, only the longest subroute is reported. For example, subroute A is finished in 2h and subroute B is finished in 4h. So, the report will only show that all clients' demands were satisfied in 4h. However, can you give an example of this error? I will check the report for the other columns, and thank you very much for contacting me about this bug and also for providing the fix!

**Comment by windowshopr** [comment]
haha well, therein lies the problem re: providing a reproducible example. I've modified the project to include my own distance matrix based on real km distances between two cities, as well as created a "duration" matrix that I use to calculate the average velocity between each city, rather than using a constant value, so my script is quite different now, but your explanation of the total does make sense, but for me, when I read "TOTAL" I would like to see the total of all subroutes, particularly when it comes to the total "Cost". My fix above just sums the last value in each subroute for the "Time" and "Distance" columns as those are accumulated throughout the subroute, but then the "Cost" column is summed for each value throughout. I guess it isn't really a "fix" as you've described it here, but I guess this could provide an alternative means of summation in the report?

**Comment by Valdecy** [comment]
All right then, I will think about how I can improve the report, maybe including more lines. The "TOTAL" line can really be misleading. Thank you very much again!
