### ISSUE TITLE
VRP with Heterogeneous Fleet

### ISSUE THREAD

**Issue by rlacjfjin** [Valdecy/pyVRP#4]
Hi,
To solve VRP with Heterogeneous Fleet, whether the local search framework is better than GA? such as LNS(ALNS) or VNS.
And is it possible to use exact method(branch and cut solver) solve heterogeneous cases?
Thanks,

**Comment by Valdecy** [comment]
Hello!
Well in general, depending on the instance, a technique may outperform the others. So is hard to say. And, yes, it is possible to use an exact method.
