### ISSUE TITLE
[Question] about multi depots and Heterogeneous Fleet

### ISSUE THREAD

**Issue by phamkhactu** [Valdecy/pyVRP#7]
Hi @Valdecy @rlacjfjin
First of all, I'd like to thank you @Valdecy for your great work and excellent contribution @rlacjfjin.

Your project works well, but I want to run with multi depots and Heterogeneous Fleet. Some vehicles **are assigned** to each depot. Now I understand that each depot has the same type of vehicles if I config 
```
n_depots    =  2           # The first n Rows of the distance_matrix are Considered as Depots
time_window = 'without'    # 'with', 'without'
route       = 'closed'     # 'open', 'closed'
model       = 'vrp'        # 'tsp', 'mtsp', 'vrp'
graph       = False        # True, False

vehicle_types = 4          # Quantity of Vehicle Types. In this examples there are 2 Types of Vehicles: A (  or 0) and B ( or 1)
fixed_cost    = [12 , 25, 12 , 25]  # Fixed Cost for Vehicle A = 12; Fixed Cost for Vehicle B = 25
variable_cost = [0.1,  1, 0.1,  1]  # Variable Cost for Vehicle A = 0.5; Variable Cost for Vehicle B = 1
capacity      = [9  ,  8, 9  ,  8]  # Capacity of Vehicle A = 9; Capacity of Vehicle B = 8
velocity      = [50 , 70, 50 , 70]  # Average Velocity of Vehicle A = 50; Average Velocity of Vehicle B = 70. The Average Velocity Value is Used as a Constant that Divides the Distance Matrix.
fleet_size    = [1  ,  1,  1,  1]   
```
In config above, each depot has 4 vehicle. **If I have 2 depots(A, B), 3 vehicles with heterogeneous capacity to depot A, 2 vehicles to with heterogeneous capacity depot B**. I don't see any configs to assign vehicles to each depot. How can I config it?

Best regards,
Tu

**Comment by Valdecy** [comment]
Hello Tu! Unfortunately, I didn't code this feature, and assigning vehicles to specific depots is impossible. However, in your config, the fleet_size indicates that you have 4 vehicles, not 4 for each depot. I would suggest the following adjustment:

n_depots    =  2           # The first n Rows of the distance_matrix are Considered as Depots
time_window = 'without'    # 'with', 'without'
route       = 'closed'     # 'open', 'closed'
model       = 'vrp'        # 'tsp', 'mtsp', 'vrp'
graph       = False        # True, False

vehicle_types = 2         
fixed_cost    = [12 , 25] 
variable_cost = [0.1,  1]  
capacity      = [9  ,  8]  
velocity      = [50 , 70]  
fleet_size    = [2 ,  2]   # if you want 4 vehicles for each depot then you need 8 vehicles so change to [4, 4]

**Comment by phamkhactu** [comment]
Thanks for your reply.

With your suggestion, if I have 4 vehicles with different capacity, I will have 4 values in each config **fixed_cost**, ..
for example:
```
fixed_cost = [12 , 25, 23 ,35]
```
It means that each depot will have 4 vehicles with [12 , 25, 23 ,35] capcacity respectively. Is it right?

**Comment by Valdecy** [comment]
Do you mean capacity = [12 , 25, 23 ,35]? Fixed cost means that every time a vehicle is used, it generates a fixed cost.  Now, answering your question, if the argument fleet_size = [ ], so you can say that every depot can use any combination of the 4 types of vehicles (note that it can decide not to use 1 or more types). If the fleet size is fixed (for example, fleet_size = [2 , 2] ) then "the problem" must be solved with at least 1 vehicle and at most 4 vehicles. Depending on "the problem" some clients may not be present in the solution (routes) due to the insufficient fleet size.

**Comment by phamkhactu** [comment]
Hi @Valdecy

I'm so sorry for making you confuse. That's right, it is **capacity**. I have tried with your advance: 2 depots, 2 type vehicle , each depot has 2 vehicles with capacities (910, 2397) respectively, 3 customers have demand (500,1220,1100). With my comprehension about VRP definition  is: 
1. vehicle needs to return to start depot.
2. vehicle can serve multi customers as long as total customer demands less than vehicle capacity
3. Optimizer cost

However, when I test with my case, **route can be established although  total capacity greater than  vehicle capacity.**
Here is my test case:
![image](https://github.com/Valdecy/pyVRP/assets/42369268/e5dc86f3-3dbc-437a-bd26-0cc48da6e533)
Here is my code:
```
import pandas as pd
import numpy as np 

from src.VRP import  build_coordinates, genetic_algorithm_vrp, plot_tour_coordinates

######################## EXAMPLE - 01 ####################################

# Load Dataset Case 1 - Distance Matrix (YES); Coordinates (NO)
distance_matrix = np.array(
    [
        [0,7600,900,4700,3600],
        [7600,0,6700,9300,7500],
        [900,6700,0,5000,3800],
        [4700,9300,5000,0,8500],
        [3600,7500,3800,8500,0]
    ]
)
coordinates     = build_coordinates(distance_matrix)
parameters      = np.array(
    [
        [0,	0,	0,	0,	0], #depot 0
        [0,	0,	0,	0,	0], #depot 1
        [500,	0,	0,	0,	0],
        [1220,	0,	0,	0,	0],
        [1100,	0,	0,	0,	0],
    ]
)

# Parameters - Model
n_depots    =  2           # The first n Rows of the distance_matrix are Considered as Depots
time_window = 'without'    # 'with', 'without'
route       = 'closed'     # 'open', 'closed'
model       = 'vrp'        # 'tsp', 'mtsp', 'vrp'
graph       = False        # True, False

# Parameters - Vehicle
vehicle_types = 2          # Quantity of Vehicle Types. In this examples there are 2 Types of Vehicles: A (  or 0) and B ( or 1)
fixed_cost    = [500000 , 500000]  # Fixed Cost for Vehicle A = 12; Fixed Cost for Vehicle B = 25
variable_cost = [1380,  2070]  # Variable Cost for Vehicle A = 0.5; Variable Cost for Vehicle B = 1
capacity      = [910  ,  2397]  # Capacity of Vehicle A = 9; Capacity of Vehicle B = 8
velocity      = [50 , 50]  # Average Velocity of Vehicle A = 50; Average Velocity of Vehicle B = 70. The Average Velocity Value is Used as a Constant that Divides the Distance Matrix.
fleet_size    = [2, 2]  # An Empty List, e.g  fleet_size = [ ], It Means that the Fleet is Infinite. Non-Empty List, e.g  fleet_size = [15, 7], Means that there are available 15 vehicles of type A and 7 vehicles of type B

# Parameters - GA
penalty_value   = 10000    # GA Target Function Penalty Value for Violating the Problem Constraints
population_size = 15       # GA Population Size
mutation_rate   = 0.10     # GA Mutation Rate
elite           = 1        # GA Elite Member(s) - Total Number of Best Individual(s) that (is)are Maintained 
generations     = 2500     # GA Number of Generations

# Call GA Function
ga_report, ga_vrp = genetic_algorithm_vrp(coordinates, distance_matrix, parameters, velocity, fixed_cost, variable_cost, capacity, population_size, vehicle_types, n_depots, route, model, time_window, fleet_size, mutation_rate, elite, generations, penalty_value, graph)

# Plot Solution
plot_tour_coordinates(coordinates, ga_vrp, n_depots = n_depots, route = route)

# Solution Report
print(ga_report)
```
My output is:
```
      Route Vehicle Activity   Job Arrive_Load Leave_Load Wait_Time Arrive_Time Leave_Time Distance     Costs
0        #1       0    start     0        2820       2820         0           0          0      0.0    500000
1        #1       0  service     3        2820       1600         0        94.0       94.0     4700   6986000
2        #1       0  service     2        1600       1100         0       194.0      194.0     9700  13886000
3        #1       0  service     4        1100          0         0       270.0      270.0    13500  19130000
4        #1       0   finish     0           0          0         0       342.0      342.0    17100  24098000
5      -//-    -//-     -//-  -//-        -//-       -//-      -//-        -//-       -//-     -//-      -//-
6  MAX TIME                                                                          342.0                   
7     TOTAL                                                                                   17100  24098000
```
![image](https://github.com/Valdecy/pyVRP/assets/42369268/170e7e9c-cf47-47e9-a2bd-9f76c77e8de2)

In my opinions, I think that it contains 2 routes from depot 0:
1. route 1: vehicle 1(capacity=900) services customer 2(demand=500)
2. route 2: vehicle 2(capacity=2397) services customer 3,4(total demand=2320)

How about you @Valdecy ? Forgive me if I wrong.
Thanks

**Comment by phamkhactu** [comment]
Thanks for your help @Valdecy

I've solved my case.
